[package]
name = "rust-npm-demo"
version = "1.0.0"
edition = "2021"
authors = ["Tushar Mathur <tusharmath@gmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
